course_name = input("What is the course code?\n>")
for i in range(1,9):
	print("%s UN0%s - check grades for previous week" % (course_name,i))
	print("%s UN0%s - reading assignment" % (course_name,i))
	print("%s UN0%s - written / programming assignment" % (course_name,i))
	print("%s UN0%s - discussion assignment" % (course_name,i))
	print("%s UN0%s - self quiz" % (course_name,i))
	print("%s UN0%s - graded quiz" % (course_name,i))
	print("%s UN0%s - peer assessment 1" % (course_name,i))
	print("%s UN0%s - peer assessment 2" % (course_name,i))
	print("%s UN0%s - peer assessment 3" % (course_name,i))
	print("%s UN0%s - rate and comment 1" % (course_name,i))
	print("%s UN0%s - rate and comment 2" % (course_name,i))
	print("%s UN0%s - rate and comment 3" % (course_name,i))
	print("%s UN0%s - learning journal" % (course_name,i))
	print("--------------------------------------------------------------------------------------")
print("%s UN09 - final exam" % (course_name))

input("Click any button to close >")